type_weaknesses = {
    'Normal': ['Fighting'],
    'Fighting': ['Flying', 'Psychic'],
    'Flying': ['Electric', 'Ice', 'Rock'],
    'Poison': ['Ground', 'Psychic'],
    'Ground': ['Water', 'Grass', 'Ice'],
    'Rock': ['Water', 'Grass', 'Fighting', 'Ground', 'Steel'],
    'Bug': ['Fire', 'Flying', 'Rock'],
    'Ghost': ['Ghost', 'Dark'],
    'Steel': ['Fire', 'Fighting', 'Ground'],
    'Fire': ['Water', 'Rock', 'Ground'],
    'Water': ['Electric', 'Grass'],
    'Grass': ['Fire', 'Ice', 'Poison', 'Flying', 'Bug'],
    'Electric': ['Ground'],
    'Psychic': ['Bug', 'Ghost', 'Dark'],
    'Ice': ['Fire', 'Fighting', 'Rock', 'Steel'],
    'Dragon': ['Ice', 'Dragon', 'Fairy'],
    'Dark': ['Fighting', 'Bug', 'Fairy'],
    'Fairy': ['Poison', 'Steel'],
}


pokemon_names = {
    'Normal': ['Pidgey', 'Rattata', 'Jigglypuff'],
    'Fighting': ['Machop', 'Mankey', 'Hitmonchan'],
    'Flying': ['Pidgey', 'Spearow', 'Charizard'],
    'Poison': ['Ekans', 'Nidoran♀', 'Bulbasaur'],
    'Ground': ['Sandshrew', 'Diglett', 'Cubone'],
    'Rock': ['Geodude', 'Onix', 'Kabuto'],
    'Bug': ['Caterpie', 'Venonat', 'Scyther'],
    'Ghost': ['Gastly', 'Haunter', 'Gengar'],
    'Steel': ['Magnemite', 'Forretress', 'Steelix'],
    'Fire': ['Charmander', 'Vulpix', 'Ponyta'],
    'Water': ['Squirtle', 'Magikarp', 'Lapras'],
    'Grass': ['Bulbasaur', 'Oddish', 'Exeggutor'],
    'Electric': ['Pikachu', 'Voltorb', 'Magneton'],
    'Psychic': ['Abra', 'Drowzee', 'Mewtwo'],
    'Ice': ['Jynx', 'Lapras', 'Articuno'],
    'Dragon': ['Dratini', 'Dragonair', 'Dragonite'],
    'Dark': ['Umbreon', 'Sneasel', 'Tyranitar'],
    'Fairy': ['Clefairy', 'Togepi', 'Wigglytuff'],
}


pokemon_n_only = ['Machop',
                      'Pidgey', 
                      'Diglett', 
                      'Sandshrew', 
                      'Charmander', 
                      'Ponyta',
                      'Oddish', 
                      'Clefairy', 
                      'Venonat',
                      'Gastly', 
                      'Dratini', 
                      'Jynx', 
                      'Geodude',
                      'Magnemite', 
                      'Ekans',
                      'Abra', 
                      'Squirtle', 
                      'Voltorb', 
                      'Rattata', 
                      'Nidoran♀',
                      'Dragonite', 
                      'Hitmonchan', 
                      'Forretress', 
                      'Gengar', 
                      'Magneton',
                      'Wigglytuff',
                      'Mankey', 
                      'Bulbasaur', 
                      'Jigglypuff', 
                      'Lapras', 
                      'Kabuto',
                      'Steelix',
                      'Sneasel', 
                      'Scyther', 
                      'Charizard',
                      'Onix', 
                      'Articuno',
                      'Pidgey', 
                      'Togepi', 
                      'Tyranitar', 
                      'Mewtwo',
                      'Lapras', 
                      'Magikarp']