type_weaknesses = {
    'Normal': ['Fighting'],
    'Fighting': ['Flying', 'Psychic'],
    'Flying': ['Electric', 'Ice', 'Rock'],
    'Poison': ['Ground', 'Psychic'],
    'Ground': ['Water', 'Grass', 'Ice'],
    'Rock': ['Water', 'Grass', 'Fighting', 'Ground', 'Steel'],
    'Bug': ['Fire', 'Flying', 'Rock'],
    'Ghost': ['Ghost', 'Dark'],
    'Steel': ['Fire', 'Fighting', 'Ground'],
    'Fire': ['Water', 'Rock', 'Ground'],
    'Water': ['Electric', 'Grass'],
    'Grass': ['Fire', 'Ice', 'Poison', 'Flying', 'Bug'],
    'Electric': ['Ground'],
    'Psychic': ['Bug', 'Ghost', 'Dark'],
    'Ice': ['Fire', 'Fighting', 'Rock', 'Steel'],
    'Dragon': ['Ice', 'Dragon', 'Fairy'],
    'Dark': ['Fighting', 'Bug', 'Fairy'],
    'Fairy': ['Poison', 'Steel'],
}


pokemon_names = {
    'Normal': ['Pidgey', 'Rattata', 'Jigglypuff'],
    'Fighting': ['Machop', 'Mankey', 'Hitmonchan'],
    'Flying': ['Pidgey', 'Spearow', 'Charizard'],
    'Poison': ['Ekans', 'Nidoran♀', 'Bulbasaur'],
    'Ground': ['Sandshrew', 'Diglett', 'Cubone'],
    'Rock': ['Geodude', 'Onix', 'Kabuto'],
    'Bug': ['Caterpie', 'Venonat', 'Scyther'],
    'Ghost': ['Gastly', 'Haunter', 'Gengar'],
    'Steel': ['Magnemite', 'Forretress', 'Steelix'],
    'Fire': ['Charmander', 'Vulpix', 'Ponyta'],
    'Water': ['Squirtle', 'Magikarp', 'Lapras'],
    'Grass': ['Bulbasaur', 'Oddish', 'Exeggutor'],
    'Electric': ['Pikachu', 'Voltorb', 'Magneton'],
    'Psychic': ['Abra', 'Drowzee', 'Mewtwo'],
    'Ice': ['Jynx', 'Lapras', 'Articuno'],
    'Dragon': ['Dratini', 'Dragonair', 'Dragonite'],
    'Dark': ['Umbreon', 'Sneasel', 'Tyranitar'],
    'Fairy': ['Clefairy', 'Togepi', 'Wigglytuff'],
}


pokemon_n_only = ['Machop',
                      'Pidgey', 
                      'Diglett', 
                      'Sandshrew', 
                      'Charmander', 
                      'Ponyta',
                      'Oddish', 
                      'Clefairy', 
                      'Venonat',
                      'Gastly', 
                      'Dratini', 
                      'Jynx', 
                      'Geodude',
                      'Magnemite', 
                      'Ekans',
                      'Abra', 
                      'Squirtle', 
                      'Voltorb', 
                      'Rattata', 
                      'Nidoran♀',
                      'Dragonite', 
                      'Hitmonchan', 
                      'Forretress', 
                      'Gengar', 
                      'Magneton',
                      'Wigglytuff',
                      'Mankey', 
                      'Bulbasaur', 
                      'Jigglypuff', 
                      'Lapras', 
                      'Kabuto',
                      'Steelix',
                      'Sneasel', 
                      'Scyther', 
                      'Charizard',
                      'Onix', 
                      'Articuno',
                      'Pidgey', 
                      'Togepi', 
                      'Tyranitar', 
                      'Mewtwo',
                      'Lapras', 
                      'Magikarp']


pokemon_moves = {
    
    'Machop': ['Low Kick', 'Karate Chop', 'Seismic Toss', 'Cross Chop'],
    'Pidgey': ['Gust', 'Quick Attack', 'Twister', 'Air Slash'],
    'Diglett': ['Scratch', 'Mud-Slap', 'Magnitude', 'Earthquake'],
    'Sandshrew': ['Scratch', 'Sand Attack', 'Swift', 'Earthquake'],
    'Charmander': ['Scratch', 'Ember', 'Flamethrower', 'Fire Spin'],
    'Ponyta': ['Ember', 'Stomp', 'Fire Blast', 'Flare Blitz'],
    'Oddish': ['Absorb', 'Acid', 'Solar Beam', 'Petal Dance'],
    'Clefairy': ['Pound', 'Sing', 'Moonblast', 'Metronome'],
    'Venonat': ['Tackle', 'Poison Powder', 'Psybeam', 'Signal Beam'],
    'Gastly': ['Lick', 'Hypnosis', 'Shadow Ball', 'Dream Eater'],
    'Dratini': ['Wrap', 'Thunder Wave', 'Dragon Pulse', 'Hyper Beam'],
    'Jynx': ['Pound', 'Powder Snow', 'Ice Punch', 'Blizzard'],
    'Geodude': ['Tackle', 'Rock Throw', 'Magnitude', 'Stone Edge'],
    'Magnemite': ['Tackle', 'Thunder Shock', 'Thunderbolt', 'Flash Cannon'],
    'Ekans': ['Wrap', 'Bite', 'Acid', 'Gunk Shot'],
    'Abra': ['Teleport', 'Psybeam', 'Shadow Ball', 'Psychic'],
    'Squirtle': ['Tackle', 'Water Gun', 'Hydro Pump', 'Aqua Tail'],
    'Voltorb': ['Tackle', 'Sonic Boom', 'Spark', 'Self-Destruct'],
    'Rattata': ['Tackle', 'Quick Attack', 'Hyper Fang', 'Crunch'],
    'Nidoran♀': ['Scratch', 'Poison Sting', 'Bite', 'Sludge Bomb'],
    'Dragonite': ['Dragon Breath', 'Wing Attack', 'Dragon Claw', 'Outrage'],
    'Hitmonchan': ['Comet Punch', 'Ice Punch', 'Thunder Punch', 'Mach Punch'],
    'Forretress': ['Tackle', 'Bug Bite', 'Toxic Spikes', 'Explosion'],
    'Gengar': ['Lick', 'Shadow Punch', 'Dark Pulse', 'Nightmare'],
    'Magneton': ['Tackle', 'Thunder Shock', 'Magnet Bomb', 'Zap Cannon'],
    'Wigglytuff': ['Pound', 'Play Rough', 'Hyper Voice', 'Dazzling Gleam'],
    'Mankey': ['Scratch', 'Low Kick', 'Karate Chop', 'Cross Chop'],
    'Bulbasaur': ['Tackle', 'Vine Whip', 'Solar Beam', 'Sludge Bomb'],
    'Jigglypuff': ['Pound', 'Rollout', 'Body Slam', 'Dazzling Gleam'],
    'Lapras': ['Water Gun', 'Ice Shard', 'Hydro Pump', 'Blizzard'],
    'Kabuto': ['Scratch', 'Mud Shot', 'Ancient Power', 'Rock Slide'],
    'Steelix': ['Iron Tail', 'Dragon Breath', 'Earthquake', 'Crunch']
}
